title: 'Users list'
breadcrumb:
    index:
        label: 'Users list'
        action: 'index'

search: 'true'

formPanelProperties:
    headerLabel: 'Filter users'
    formFields:
        name:
            label: 'Name'
            field: 'name'
            type: 'text'
            conditionType: 'like'
            col: '6'
    footerListButtons:
        submit:
            buttonType: 'button'
            label: 'Filter'

tablePanelProperties:
    headerLabel: 'Users list'
    headerListButtons:
        create:
            buttonType: 'link'
            color: 'success'
            label: 'Create a user'
            action: 'create'
            modal: 'true'
            size: 'xs'
    tableFields:
        buttons:
            multipleFields:
            update:
                icon: 'pencil'
                modal: 'true'
                action: 'update'
            delete:
                icon: 'trash'
                color: 'danger'
                action: 'delete'
                confirm: 'Do you want really want to delete this user ?'
            resetPassword:
                icon: 'lock'
                color: 'warning'
                action: 'resetPassword'
                confirm: 'Do you want really want to reinitialize and send a new password to this user ?'
        id:
        email:
